pool:
  name: Mynewpoolagent

variables:
  BuildConfiguration: "release"
  BuildPlatform: "any cpu"

stages:
  - stage:
    displayName: Build
    jobs:
      - job:
        displayName: Build_And_Publish
        steps:
          - task: NuGetCommand@2
            displayName: Nuget_Restore
            inputs:
              command: 'restore'
              restoreSolution: '**/*.sln'
              feedsToUse: 'select'
          - task: VSBuild@1
            displayName: Build_Solution
            inputs:
              solution: '**\*.sln'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'
              platform: '$(BuildPlatform)'
              configuration: '$(BuildConfiguration)'
          - task: PublishBuildArtifacts@1
            displayName: Publish_Artifact
            inputs:
              PathtoPublish: '$(build.artifactstagingdirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
  
  - stage: 
    displayName: Infrastructure_Provisioning
    jobs:
      - job:
        displayName: Terraform
        steps:
          - task: TerraformTaskV3@3
            displayName: Terraform_Init
            inputs:
              provider: 'azurerm'
              command: 'init'
              workingDirectory: '$(System.DefaultWorkingDirectory)\automation\terraform'
              backendServiceArm: 'Free Trial(a1bba573-9004-46f4-b502-223c729c1969)'
              backendAzureRmResourceGroupName: 'rg-tf-backends'
              backendAzureRmStorageAccountName: 'azb23tfremotebackend'
              backendAzureRmContainerName: 'tfremotebackend'
              backendAzureRmKey: 'dev.terraform.tfstate'
          - task: TerraformTaskV3@3
            displayName: Terraform_Plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              workingDirectory: '$(System.DefaultWorkingDirectory)\automation\terraform'
              environmentServiceNameAzureRM: 'Free Trial(a1bba573-9004-46f4-b502-223c729c1969)'
          - task: TerraformTaskV3@3
            displayName: Terraform_Apply
            inputs:
              provider: 'azurerm'
              command: 'apply'
              workingDirectory: '$(System.DefaultWorkingDirectory)\automation\terraform'
              environmentServiceNameAzureRM: 'Free Trial(a1bba573-9004-46f4-b502-223c729c1969)'
  - stage: 
    displayName: Release_To_Dev
    jobs:
      - job:
        displayName: Terraform
        steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Free Trial(a1bba573-9004-46f4-b502-223c729c1969)'
              appType: 'webApp'
              WebAppName: 'my-webapps-001'
              packageForLinux: '$(System.DefaultWorkingDirectory)/_satishkalyani.Updated_PartsUnlimited/drop/PartsUnlimitedWebsite.zip'